"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import time
start = time.time()
a = 1
b = 1
g = 0
for i in range(1,500):
    a,b=b,a+b
    if (a <= 4000000 and a % 2 == 0):
        for i in range(1):
            g = a + g
print(g)
elapsed = time.time() - start
print("Time: {:.5f} seconds".format(elapsed))